### ISSUE TITLE
Support The Graph

### ISSUE THREAD

**Issue by geastwood** [litentry/api-gateway#47]
The Graph (https://thegraph.com/en/) is an indexing protocol for evm based network, It's desirable to have api-gateway to support **The Graph**

**Comment by geastwood** [comment]
Let's discuss here the specification here.

**Comment by bdmason** [comment]
Start [here](https://thegraph.com/docs/en/developer/quick-start/). In a previous meeting I suggested that we had a choice between a hosted service and the standard decentralized network, this in't the case, the hosted service is for subgraphs that index other networks outside of Ethereum mainnnet. Whilst there will be some work with Binance, the majority of the Phala integration is using Phala balances and contract interactions on the mainnet.

**Comment by bdmason** [comment]
We now have a working subgraph, I'm deploying to one in my own name, and I suggest other developers do the same so we can test easily without overwriting each other's instance. Once the project is more stable in the next week or 2 I'll create a Litentry owned subgraph.
