### ISSUE TITLE
Add subgraphs to API Gateway

### ISSUE THREAD

**Issue by bdmason** [litentry/api-gateway#51]
The eth and bsc subgraphs as well as the khala subgraph need adding to the gateway as remote schemas.

- [x] deploy eth subgraph
- [x] deploy bsc subgraph
- [ ] deploy khala subgraph (needs a pipeline tweak to work around existing issue with subsquid deployments)
- [ ] add remote schemas to API GW

**Comment by geastwood** [comment]
Closed without two items being checked?

**Comment by bdmason** [comment]
Just forgot to check them when I was tidying up the board.
