### ISSUE TITLE
Remote schema failure testing

### ISSUE THREAD

**Issue by bdmason** [litentry/api-gateway#89]
We need to understand what happens to our graph when a remote schema fails in these scenarios:

- a single query errors (do other queries in the same request resolve - _both within the same subschema and outside it_)?
- an entire subgraph goes down (does the rest of our graph continue to function?)

**Comment by geastwood** [comment]
This sounds super interesting to learn about, make sure to log the finding.

**Comment by markdavison** [comment]
If the squid is down then queries to the graph continue to work. 

If the query should return data from both then it will also fail.

When our squid is down:

Succeeds:
```
query MyQuery {

  erc20Accounts(first:1) {
    id
  },
}
```

Fails:
```
query MyQuery {

  erc20Accounts(first:1) {
    id
  },
    substrateAccounts(limit: 1) {
    id
  },
}
```

Fails:
```
query MyQuery {

    substrateAccounts(limit: 1) {
    id
  },
}
```

**Comment by bdmason** [comment]
Thanks @markdavison.
